language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t jorortram/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jorortram/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-west-1-989084156240"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"