language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t jorortram/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jorortram/docker-react npm run test